### ISSUE TITLE
Textnote.ByStringAndPosition not working for me

### ISSUE THREAD

**Issue by sfong1963** [andydandy74/ClockworkForDynamo#104]
### Description
I am using the Textnote.ByStringAndPosition node.  It is suddenly not actually writing to the drafting view.  It worked for me in the past

### Expected behaviour
I expected text to be written to a drafting view.  Is there something about this that I am doing wrong?

### My setup
- Operating System: Windows 10
- Dynamo version: Had been on 1.0, but downgraded to 0.9 to test
- Revit version & build number: 2016 - 0.9

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running one of the *supported* Clockwork versions
- [x] I am running the *latest available version* of Clockwork
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
![testwriteindraftingview](https://cloud.githubusercontent.com/assets/10119734/15784804/cc79b678-2979-11e6-89bd-37ac40761de4.png)

**Comment by andydandy74** [comment]
You seem to be using an older version of Clockwork (and the TextNote node). It now looks like this:
![textnotenew](https://cloud.githubusercontent.com/assets/3014437/15785693/d7bc31ca-29b8-11e6-8fd2-d98a2b169b5a.PNG)
The node on your screenshot looks like a node from Clockwork for Dynamo **0.7.x**...
Please update Clockwork (and make sure you do not have multiple versions of Clockwork installed side by side) and reopen this issue if the problem persists.

**Comment by andydandy74** [comment]
Also, the node you *do* have should work fine (at least in Dynamo 0.7.x) as long as you provide actual *vectors* for the last two inputs.

**Comment by sfong1963** [comment]
Ah!  Somehow my dynamo lost the downloaded packages, and I had to
re-install.  I thought that I had installed the latest, however I did have
a “text align right” node that had nowhere to go!  That explains it.



Sorry, new to all this and fighting it.



Thanks so much.



*Steve Fong*

BIM / CAD Manager



*From:* Andreas Dieckmann [mailto:notifications@github.com]
*Sent:* Friday, June 3, 2016 11:30 AM
*To:* andydandy74/ClockworkForDynamo <ClockworkForDynamo@noreply.github.com>
*Cc:* sfong1963 <jsf@overlandpartners.com>; Author <
author@noreply.github.com>
*Subject:* Re: [andydandy74/ClockworkForDynamo]
Textnote.ByStringAndPosition not working for me (#104)



You seem to be using an older version of Clockwork (and the TextNote node).
It now looks like this:
[image: textnotenew]
<https://cloud.githubusercontent.com/assets/3014437/15785693/d7bc31ca-29b8-11e6-8fd2-d98a2b169b5a.PNG>
The node on your screenshot looks like a node from Clockwork for Dynamo
*0.7.x*...
Please update Clockwork (and make sure you do not have multiple versions of
Clockwork installed side by side) and reopen this issue if the problem
persists.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/andydandy74/ClockworkForDynamo/issues/104#issuecomment-223627207>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJpqNhOf2uaXMkcfWQwf1W4zlZCHxkJzks5qIFaYgaJpZM4Itq2m>
.

**Comment by sfong1963** [comment]
Will 0.9 clockwork work with Dynamo 1.0?



*Steve Fong*

BIM / CAD Manager



*From:* Andreas Dieckmann [mailto:notifications@github.com]
*Sent:* Friday, June 3, 2016 11:32 AM
*To:* andydandy74/ClockworkForDynamo <ClockworkForDynamo@noreply.github.com>
*Cc:* sfong1963 <jsf@overlandpartners.com>; Author <
author@noreply.github.com>
*Subject:* Re: [andydandy74/ClockworkForDynamo]
Textnote.ByStringAndPosition not working for me (#104)



Also, the node you *do* have should work fine (at least in Dynamo 0.7.x) as
long as you provide actual *vectors* for the last two inputs.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/andydandy74/ClockworkForDynamo/issues/104#issuecomment-223627577>,
or mute the thread
<https://github.com/notifications/unsubscribe/AJpqNsnt9ppgrRDjgqpg4VsF09m7bmq2ks5qIFbogaJpZM4Itq2m>
.

**Comment by andydandy74** [comment]
Most likely yes, although I haven't tested that particular node yet.
