### ISSUE TITLE
Room.Boundary not work in 2017 due to api changes

### ISSUE THREAD

**Issue by eibre** [andydandy74/ClockworkForDynamo#106]
Room.Boundary not work in 2017 due to api changes

See this thread on dynamo forum: https://forum.dynamobim.com/t/revit-2017-room-boundaries/5456/3

**Comment by andydandy74** [comment]
This is likely addressed in #57

**Comment by eibre** [comment]
Well Konrad updated it to 2016, but the GetCurve() method replaced the curve parameter in 2017. So that has to be addressed as well.

**Comment by andydandy74** [comment]
You're right, of course. This should be fixed with this commit: b4cada1935021a7ab677b9ff8e1fd19316932fc1
It will be available soon in Clockwork for Dynamo 1.x
