### ISSUE TITLE
Add a Time.StartLine node

### ISSUE THREAD

**Issue by chojje** [andydandy74/ClockworkForDynamo#107]
### Description
I've been using Clockwork to time the evaluation of a Dynamo definition. However, since nothing forces the entire definition to rerun when the definition has been run the first time, the starting time of the initial LapTime node won't change, causing the output total time to be measured from the first evaluation rather than the most recent.

### Improvement
To fix this, adding a node Time.StartLine (sticking with the athletics allegory), which takes a boolean toggle as input, and simply reruns all of the definition every time the toggle is toggled, would make the timer even more useful.

It's simple to work around as depicted in the image below, but this addition could improve the Clockwork's function as a Dynamo timer.

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running one of the *supported* Clockwork versions
- [x] I am running the *latest available version* of Clockwork
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version

![image](https://cloud.githubusercontent.com/assets/21218833/17972581/7ff487fe-6adf-11e6-86a7-2fd9230578a7.png)

**Comment by andydandy74** [comment]
@chojje - I'll do you one better: I added a boolean toggle to the Time.LapTime node. It does what you asked for, but this way you can also use the node to force re-execution of other parts of your graph. Plus, I have one node less to maintain. ;-)
348cdce035036330dac202607f99e603a1bbe464
This will be in Clockwork 1.0.2
