### ISSUE TITLE
Wall.ByFace doesn't work...

### ISSUE THREAD

**Issue by calmwish** [andydandy74/ClockworkForDynamo#119]
### Description
Hello,

1) I made a Conceptual Mass Family, simply a Line and have extruded it as surface.
2) load this family to Revit Project
3) put an instance of this family in Project
4) get face of instance by Dynamo
5) used Wall.ByFace Node and CPU running permant. (It seems, Python Part running endless)

I tried with Revit 2016 and Revit 2017.1 with both Dynamo Version 0.9.1 and 1.2 but same problem.
How can I solve this matter? Help!

### Expected behaviour
create Wall by Face

### My setup
- Operating System: W7
- Dynamo version: 0.9.1 and 1.2
- Revit version & build number: 2016 and 2017.1

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [X] I am running the *supported* Clockwork version
- [X] I am running the *latest available version* of Clockwork
- [X] My installed version of Clockwork matches the Dynamo version it's installed for
- [X] I do *not* have multiple versions of Clockwork installed for one Dynamo version

**Comment by andydandy74** [comment]
@calmwish - can you please provide your dyn and rvt files?
FYI: There was a similar (yet unresolved) issue on the forum.

**Comment by calmwish** [comment]
Sure I can.
You can find Dynamo (1.2) and Revit (2017) File here.


[Clockwork.zip](https://github.com/andydandy74/ClockworkForDynamo/files/547217/Clockwork.zip)

**Comment by andydandy74** [comment]
@calmwish - Works for me - as soon as I switch the graph to manual mode. (Revit 2017 & Dynamo 1.2)
![capture](https://cloud.githubusercontent.com/assets/3014437/19822333/331ce7ee-9d63-11e6-867c-e5de38921ff3.PNG)
