### ISSUE TITLE
If view in list don't have phase (drafting), node drops it in output

### ISSUE THREAD

**Issue by MaxSpecs** [andydandy74/ClockworkForDynamo#121]
### Description
This node crops sequence, in my case views with no phase (drafting) will be dropped from list at output

### Expected behaviour
In Python Script node i modify line 15 to elementlist.append("") instead of elementlist.append(list()).
I am not developer, can't argue if you had good reason for original code.  It just when i feed list with 20 objects i expect to get 20 objects out as well.

### My setup
- Operating System: Windows 7
- Dynamo version: 1.2
- Revit version & build number: 2015, 20160512_0715(x64)

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ ] I am running the *supported* Clockwork version
- [x] I am running the *latest available version* of Clockwork
- [ ] My installed version of Clockwork matches the Dynamo version it's installed for
- [ ] I do *not* have multiple versions of Clockwork installed for one Dynamo version

**Comment by andydandy74** [comment]
Which node is this about?

**Comment by andydandy74** [comment]
I am clsoing this as there is not enough information provided. Please feel free to re-open and supply more information.
