### ISSUE TITLE
Element.ById not working (cause of ReturnListOrSingleValue)

### ISSUE THREAD

**Issue by AdrienP53** [andydandy74/ClockworkForDynamo#125]
### Description
First of all, I'm very sorry if it's not the place to ask my question, I don't find any mail adress to contact you...
I just switch into the 1.2.1 version of Dynamo and I found some good stuff in it. But I use in all of my dynamo program the node Element.ById (used to link excel and revit). BUT, it's not working anymore cause of the node ReturnListOrSingleValue wich is inside the Element.ById node...

I really would like to help you correcting it if you want my help despite of I never programed in python before :)

EDIT: Ok so it works now, I placed all the components of ReturnListOrSingleValue directly in the Element.ById node and it's ok now...
Have a nice day !

### Expected behaviour
I expect to work like the ancient version.

### My setup
- Operating System: Windows 7
- Dynamo version: 1.2.1
- Revit version & build number: 
16.0.1185.0 
20161004_0715(x64) 
Update7 for R2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *supported* Clockwork version
- [X] I am running the *latest available version* of Clockwork
- [X] My installed version of Clockwork matches the Dynamo version it's installed for
- [X] I do *not* have multiple versions of Clockwork installed for one Dynamo version

**Comment by andydandy74** [comment]
This seems to work in 1.3
