### ISSUE TITLE
'FamilyInstance.ByPointInView' returns NULL on some family types

### ISSUE THREAD

**Issue by blankblank13** [andydandy74/ClockworkForDynamo#134]
### Description
Hi Andy, 

I am currently experiencing that this custom node returns null when I input one family type, but works as intended when I input a different family type.

Please find attached snapshot examples.

I've reviewed and experimented with different inputs but I'm not able to work out why this is occurring.

If you could assist that would be much appreciated! I have my script all set up and this is the final piece of the puzzle.

Many thanks in advance.

Thanks
Melvin

[Doc1.docx](https://github.com/andydandy74/ClockworkForDynamo/files/1158696/Doc1.docx)

### Expected behaviour
Family instances placed as per the points provided as input to the node.

### My setup
- Operating System: Win 7 Enterprise
- Dynamo version: 1.3.0.875
- Revit version & build number: Revit 2016 & 16.0.1185.0 20161004_0715(x64) Update7 for R2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [Y] I am running the *supported* Clockwork version
- [Y] I am running the *latest available version* of Clockwork
- [Y] My installed version of Clockwork matches the Dynamo version it's installed for
- [Y] I do *not* have multiple versions of Clockwork installed for one Dynamo version

**Comment by andydandy74** [comment]
Just trying to rule out a couple of likely causes here:
1. Are you placing both families in the same view or or at least the same view type?
2. Is the second family *not* a model family?

**Comment by blankblank13** [comment]
Andreas, thanks for the quick response! To answer the above:

1. Yes it is the same view (drafting view). The only input I change between the two runs of my script is the family type
2. They are both Detail Item families (I am placing symbols in a drafting view for a schematic)

**Comment by andydandy74** [comment]
Weird. Can you reproduce this behaviour with both families in a blank project file and share that model?

**Comment by blankblank13** [comment]
Yes, I've just tried it in a blank project. Please find attached project file and test .dyn file.
[20170720 TEST.zip](https://github.com/andydandy74/ClockworkForDynamo/files/1162211/20170720.TEST.zip)

**Comment by andydandy74** [comment]
@blankblank13 sorry for the delay, didn't manage to look at your file before my vacation. 
The reason why the second family isn't working is because it's a line-based detail item. You can use Clockwork's DetailComponent.ByCurve node instead in order to place that particular family.

**Comment by blankblank13** [comment]
No worries Andreas. Thanks a lot for having a look - I did not realise that it was line-based and that it would act differently.
