### ISSUE TITLE
Elements.FilterByParameterValueAndCondition Not Returning Expected Result

### ISSUE THREAD

**Issue by ChrisHildebran** [andydandy74/ClockworkForDynamo#157]
### Description
I'm attempting to use the Clockwork Nodes "Elements.FilterByParameterValueAndCondition" along with "Elements.FilterByName" in a Dynamo Graph.

The node "Elements.FilterByName" works as expected; node "Elements.FilterByParameterValueAndCondition" doesn't. 

### Expected behaviour
Im expecting the node in question to filter the list of Elements based on the value of a parameter.

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.1.1736
- Revit version & build number: 17.0.1146.0 | 20170816_0615(x64) | 2017.2.2 

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x ] I am running the *supported* Clockwork version
- [x ] I am running the *latest available version* of Clockwork
- [x ] My installed version of Clockwork matches the Dynamo version it's installed for
- [x ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
![screenshot](https://user-images.githubusercontent.com/32686889/31410672-2597d6e8-adc4-11e7-9b13-d4eaf577bcbd.png)

**Comment by ChrisHildebran** [comment]
Another screenshot using different Parameter/Value pair.
![screenshot](https://user-images.githubusercontent.com/32686889/31410970-0c8ef2ca-adc5-11e7-8f03-84362991736c.png)

**Comment by andydandy74** [comment]
The ```func``` input needs an actual function, not a parameter name:
![grafik](https://user-images.githubusercontent.com/3014437/31419242-fa636394-ae3a-11e7-8c7a-0a6a41ab03f6.png)
(This example finds all walls with a base offset lower than 500 mm)
