### ISSUE TITLE
Clipboard.SentTo crashes dynamo and revit if you send an empty string

### ISSUE THREAD

**Issue by wynged** [andydandy74/ClockworkForDynamo#159]
### Description
If for some reason a script sends and empty string into the Clipboard.SentTo node, it reliably crashes dynamo and Revit.  I'm using Revit 2018.2

### Expected behaviour
(Please fill in)

### My setup
- Operating System: ..........Windows......
- Dynamo version: ...........1.3.....
- Revit version & build number: ....2018.2............

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [* ] I am running the *supported* Clockwork version
- [ *] I am running the *latest available version* of Clockwork
- [ *] My installed version of Clockwork matches the Dynamo version it's installed for
- [ *] I do *not* have multiple versions of Clockwork installed for one Dynamo version

**Comment by wynged** [comment]
I made a new node with the following code.  It doesn't have all that thread stuff.... but I'm not sure I need that.
`
clr.AddReference("System.Windows.Forms")
import System.Windows.Forms


if not IN[0] == "":
	try:
		System.Windows.Forms.Clipboard.SetText(str(IN[0]))
		o = str(IN[0])
	except:
		o = "Failed to Write to Clipboard"
else:
	System.Windows.Forms.Clipboard.SetText("tried to copy empty")
	o = "no empty strings allowed"
`

**Comment by andydandy74** [comment]
Thanks for reporting. Fix will be in the next version of Clockwork
