### ISSUE TITLE
Document.SynchronizeWithCentrale

### ISSUE THREAD

**Issue by DanielHurtubise** [andydandy74/ClockworkForDynamo#170]
### Description
Improvement

### Expected behaviour
Works like a charm except that it would be nice to have a boolean to decide if we run it or not. Typically i use it at the end of a script and sometimes i want to be able to not STC.
Say when a user cancel from a Data-Shapes dialog,

### My setup
- Operating System: Windows 10 C64
- Dynamo version: 1.3.2
- Revit version & build number: 2018.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ X] I am running the *supported* Clockwork version
- [X ] I am running the *latest available version* of Clockwork (1.31)
- [ X] My installed version of Clockwork matches the Dynamo version it's installed for
- [ X] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [X ] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
@DanielHurtubise Good suggestion. This will be part of the upcoming update for Clockwork.
