### ISSUE TITLE
String.MatchRegularExpression

### ISSUE THREAD

**Issue by Thomas84** [andydandy74/ClockworkForDynamo#172]
### Description
in your Node in the python code you use the search() method instead of the match() method. But you named the node "String.MatchRegularExpression".

![image](https://user-images.githubusercontent.com/5624034/35759642-284fa20a-087b-11e8-9244-fa8aa3d35b46.png)

It works for me, but it is a bit misleading compared to the regex documentation:

http://ironpython-test.readthedocs.io/en/latest/library/re.html#re-syntax

![image](https://user-images.githubusercontent.com/5624034/35759514-76e56e28-087a-11e8-8bcb-9c25dac1f46f.png)

### Expected behaviour
does it make sense to change the name of the node?

### My setup
- Operating System: win10
- Dynamo version: 1.3.2
- Revit version & build number: 2018.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ x] I am running the *supported* Clockwork version
- [ x] I am running the *latest available version* of Clockwork
- [ ] My installed version of Clockwork matches the Dynamo version it's installed for
- [ x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
@Thomas84 Thanks for reporting. In the next release of Clockwork, this node shall be renamed to ```String.ContainsRegularExpression```. I have also added another node that uses the ```match()``` method called ```String.StartsWithRegularExpression```.
