### ISSUE TITLE
Revit 2018 set workset python change

### ISSUE THREAD

**Issue by wynged** [andydandy74/ClockworkForDynamo#173]
### Description
The setworkset node doesn't work.  Changed python to show error and it said "int object has no property IntegerValue", so I removed looking for that property and it worked.

### Expected behaviour
(Please fill in)

change of workset.  here's the new python script code I inserted.  simple change:
```
import clr
clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *

clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

doc = DocumentManager.Instance.CurrentDBDocument
faminsts = UnwrapElement(IN[0])
ws = UnwrapElement(IN[1])
booleans = list()
TransactionManager.Instance.EnsureInTransaction(doc)
for item in faminsts:
	try:
		param = item.get_Parameter(BuiltInParameter.ELEM_PARTITION_PARAM)
		param.Set(ws.Id)
		booleans.append(True)
	except BaseException as e:
		booleans.append(e)
TransactionManager.Instance.TransactionTaskDone()
OUT = (faminsts,booleans)
```

### My setup
- Operating System: ................
- Dynamo version: ................
- Revit version & build number: ................

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *supported* Clockwork version
- [x] I am running the *latest available version* of Clockwork
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
Sure the node works:
![grafik](https://user-images.githubusercontent.com/3014437/36012541-11fb4dcc-0d5f-11e8-9e94-98e01990254e.png)
You're likely using it with the archi-lab Workset nodes. They wrap up the original Revit API objects in a warpper class that has slightly different properties (e.g. the Id property is an integer, not an ElementId).
Use the Workset nodes from Clockwork and you should be fine.

**Comment by wynged** [comment]
You are of course quite correct!  Thanks for helping me understand.

**Comment by ksobon** [comment]
@andydandy74 you could handle that Id in your code. Just bear in mind that all Dynamo nodes return Ids as Integers and eventually one day we will wrap Worksets into OOTB Dynamo nodes, and they will return Integers. Why not handle that today?

**Comment by andydandy74** [comment]
@ksobon Definitely not today, but you're right - let's keep this issue open.

**Comment by andydandy74** [comment]
@wynged @ksobon Fix wil be in the next release.
