### ISSUE TITLE
SpotElevation.ByFloorPlanAndPoint - Update to take Ceiling Plans

### ISSUE THREAD

**Issue by PatrickPDPS** [andydandy74/ClockworkForDynamo#175]
### Description
I wanted to ask if it was possible that you could update the node "SpotElevation.ByFloorPlanAndPoint" to also accept ceiling plan views. I have a workflow right now that applies a spot elevation to a ceiling plan view, and it works so long as I modify the node's input to take ceiling plans rather floor plans.
Thanks, 

### Expected behaviour
Accept Ceiling Plan Views

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.2
- Revit version & build number: 2018.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x ] I am running the *supported* Clockwork version
- [x ] I am running the *latest available version* of Clockwork
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
@PatrickPDPS Thanks for reporting - this will be in the next release.
