### ISSUE TITLE
Project Position Node Error

### ISSUE THREAD

**Issue by Amehr** [andydandy74/ClockworkForDynamo#176]
### Description
Clockwork/Project Position doesn't show correct project base info

![clockwork](https://user-images.githubusercontent.com/36696066/36510067-e9d853f6-17b5-11e8-9831-abf7a4ba3568.jpg)

### Expected behaviour
project base info/parameters

### My setup
- Operating System: Windows 8
- Dynamo version: 1.3.2.2480
- Revit version & build number: 2018.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ x ] I am running the *latest available version* of Clockwork
- [ x ] My installed version of Clockwork matches the Dynamo version it's installed for

**Comment by andydandy74** [comment]
Thanks for letting me know. I ran some tests and it seems that the numbers that this node outputs will diverge from the project base point coordinates once the project base point is moved in an unclipped state. I find that counter-intuitive, but it seems to be in accordance with the Revit documentation:
https://knowledge.autodesk.com/support/revit-products/learn-explore/caas/CloudHelp/cloudhelp/2015/ENU/Revit-Collaborate/files/GUID-0625D4E1-4EE9-4848-8B44-73A75D1896DB-htm.html
So programmatically, nothing needs to be fixed here. Nevertheless, the behaviour should be documented better in the node description.

**Comment by Amehr** [comment]
Thanks for the update :)
