### ISSUE TITLE
Make Group.IsMirrored more robust (restored excluded members)

### ISSUE THREAD

**Issue by andydandy74** [andydandy74/ClockworkForDynamo#195]
https://forum.dynamobim.com/t/listorder-groupelements-not-the-same/22904

**Comment by 3Pinter** [comment]
@andydandy74 ,

Your suggestion to check if familytype are the same could work but isn't 'bulletproof'. 

Create a group with 3 instances, all of the same family, same type. 
the first instance is mirrored, the other 2 aren't.

Situation: the first instances is excluded, and restored.
New situation: the first instances becomes the last instance.
Result: indexnumber has changed, but family type remain the same, so no flag for a false comparison, and therefor 'not mirrored' will return if checked.

The 'most robust' option I came up with was:
- get all instances in a group and
- check if there is an unique instance (only one) in that group
- if so: lucky. that's the one you want to compare
- if not: other methods.

**Comment by andydandy74** [comment]
added a warning in the description and added family type checking in the code. not bulletproof, but at least a little more robust.
