### ISSUE TITLE
All View-Dependent Family Instances Of Category and Dependent Views

### ISSUE THREAD

**Issue by GMcDowellJr** [andydandy74/ClockworkForDynamo#197]
### Description
All View-Dependent Family Instances Of Category doesn't work on Dependent Views

### Expected behaviour
All View-Dependent Family Instances Of Category works on Dependent Views

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.3.4651
- Revit version & build number: 2017.2 -- 20171027_0315(x64)

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x ] I am running the *supported* Clockwork version
- [x ] I am running the *latest available version* of Clockwork
- [x ] My installed version of Clockwork matches the Dynamo version it's installed for
- x[ ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
@GMcDowellJr - This is fixed in the upcoming release of Clockwork
