### ISSUE TITLE
Wall.Orientation does not update with shape handle flip

### ISSUE THREAD

**Issue by BlakeNicholson** [andydandy74/ClockworkForDynamo#202]
### Description
The wall.orientation node does not update its vector when the wall shape handle is flipped, reversing the wall's facing direction.
### Expected behaviour
The wall orientation vector should always be normal to the exterior side of a wall element.

### My setup
- Operating System: Windows 10
- Dynamo version: 1.3.3
- Revit version & build number: 2017.2 - 20170419_0315, Clockwork 1.31.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *supported* Clockwork version
- [x] I am running the *latest available version* of Clockwork
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
Good catch. I'll try to include this in the next release.

**Comment by andydandy74** [comment]
This will be in Clockwork 1.32.0 and 2.1.0. Again, thanks for reporting.
