### ISSUE TITLE
List.randomElements on Dynamo 2.0

### ISSUE THREAD

**Issue by DanielHurtubise** [andydandy74/ClockworkForDynamo#203]
### Description
The node doesn't return anything

### Expected behaviour
Returning a list of Family Type

### My setup
- Operating System:Windows 10 x64
- Dynamo version: 2.0.1.5065
- Revit version & build number: 2019 & 19.0.0.405
- Clockwork: 1.31.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [ ] I am running the *supported* Clockwork version
- [ ] I am running the *latest available version* of Clockwork
- [ ] My installed version of Clockwork matches the Dynamo version it's installed for
- [ ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ ] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

![image](https://user-images.githubusercontent.com/4299930/42806500-e61c68d6-89ae-11e8-9a3a-3b1272dc159c.png)

**Comment by andydandy74** [comment]
Hi Daniel,
that may very well be the case - a lot of nodes had to be rewritten. This particular node has already been converted and tested, though. Can you try out the (not yet released) 2.0 version of Clockwork and report back if that solves your issue? (Just delete all 1.x nodes in your Clockwork package dir and paste the 2.x nodes in there...)
https://github.com/andydandy74/ClockworkForDynamo/tree/master/nodes/2.x

**Comment by DanielHurtubise** [comment]
The name has changed in 2.0 right?

**Comment by andydandy74** [comment]
It should show up under Clockwork > List > Generate > RandomList
If it doesn't show up in searches, I would not be surprised since search has been kinda sucky for a looong time... :-(

**Comment by andydandy74** [comment]
Looking at your screenshot it looks as though you still have 1.0 nodes in there. Better to delete them all and just use the 2.0 nodes.

**Comment by DanielHurtubise** [comment]
Ok my bad., Is there a quick way to download all the nodes?
Should i also use another folder like Clockwork for Dynamo 2.x ?

**Comment by andydandy74** [comment]
![grafik](https://user-images.githubusercontent.com/3014437/42845691-0d19de2e-8a17-11e8-87e7-eb5e7f139ba9.png)
You could publish it as a local package. I can't really say when I'll release Clockwork 2, but it might be another couple of weeks.

**Comment by DanielHurtubise** [comment]
First, a good news :)
No more red node
![image](https://user-images.githubusercontent.com/4299930/42864032-5873f71c-8a65-11e8-902f-3cdf87751c2b.png)

But it still doesn't return a list.. but hey... it's going forward :)

**Comment by andydandy74** [comment]
Works fine on my end. Make sure that none of the node inputs are disabled (right-click on input and see if "Use default value" is checked).

**Comment by DanielHurtubise** [comment]
I should have know from... data-shapes :)
![image](https://user-images.githubusercontent.com/4299930/42886367-adf167cc-8aa3-11e8-99a8-7159e70c6336.png)
