### ISSUE TITLE
All Family Types of Category

### ISSUE THREAD

**Issue by DanielHurtubise** [andydandy74/ClockworkForDynamo#204]
### Description
Nodes return Function

### Expected behaviour
Return a list of families

### My setup
- Operating System: Windows 10 x64
- Dynamo version:2.0.1.5065
- Revit version & build number: 2019

![image](https://user-images.githubusercontent.com/4299930/42868932-d7688ec6-8a73-11e8-87d0-4a03692d88af.png)

:) thanks a lot

**Comment by andydandy74** [comment]
Works fine on my end. Make sure that none of the node inputs are disabled (irght-click on input and see if "Use default value" is checked).

**Comment by mjkkirschner** [comment]
This might also be a bug that was fixed in the latest daily build.
