### ISSUE TITLE
All View-Dependent Family Instances Of Category

### ISSUE THREAD

**Issue by MarkAckerley** [andydandy74/ClockworkForDynamo#213]
### Description
All View-Dependent Family Instances Of Category does not collected tags to linked elements apart from Room Tags

### Expected behaviour
Tags to linked elements can be collected

### My setup
- Operating System: Windows
- Dynamo version: 1.3 & 2.01
- Revit version & build number: 2018.2

### Housekeeping
Please **make sure these boxes are checked** before submitting your issue:
- [X ] I am running the *supported* Clockwork version
- [ X] I am running the *latest available version* of Clockwork
- [ X] My installed version of Clockwork matches the Dynamo version it's installed for
- [ X] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ X] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

P.S Thank you for such an awesome package!

**Comment by andydandy74** [comment]
I can reproduce this with WallTags. An internal error occurs when passing the filtered collector to the ToElements() method. Not sure yet how to fix this.

**Comment by andydandy74** [comment]
Thanks. Relevant Dynamo issue here:
https://github.com/DynamoDS/DynamoRevit/issues/1840
I'll see if I can get it to work with @dimven 's approach.

**Comment by MarkAckerley** [comment]
Konrad is also getting involved here... 

https://forum.dynamobim.com/t/how-to-identify-orphaned-tags/16076/8

The Big Guns are on it :)

**Comment by andydandy74** [comment]
Sorry for leaving this so long. Apparently it works in later versions (tested in 2022)
