### ISSUE TITLE
Element.CopyByVector Deletes items created in previous run

### ISSUE THREAD

**Issue by BlakeNicholson** [andydandy74/ClockworkForDynamo#214]
**Describe the bug**
Element.CopyByVector works great for the first run. If you change the inputs and run it again, it will delete the elements created in the previous run.

**Steps to Reproduce**
I used it to copy spot slopes onto the top faces of a shaped edited slab. 
1. Draw spot slope in revit, create reference to it in dynamo.
2. Get spot slope location point.
3. Reference a shape edited slab.
4. Find centre point of the faces that are on the top of the slab.
5. Get vector between faces and spot slope location.
6. Use Element.CopyByVector.
7. Change inputs and re run without closing dynamo.

**Expected behavior**
The node should be able to be re run without deleting previously created elements.

**My setup**
- Operating System: Windows 10
- Dynamo version: 1.3.3
- Revit version & build number: 2017.2 - 20170419_0315, Clockwork 1.31.2

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running a *supported* Clockwork version
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
Hi. This is due to element binding and therefore is behaving as expected. 
https://forum.dynamobim.com/search?q=element%20binding
