### ISSUE TITLE
Element.Materials Clockwork node (single element into list)

### ISSUE THREAD

**Issue by MatteoCapoferri** [andydandy74/ClockworkForDynamo#215]
Hi All, the python script behind the node works with single element (the first in the list) but not for all elements, question is would it be possible to work also with a list of elements (walls/floors/...) ?

Thanks
![006](https://user-images.githubusercontent.com/36993906/43785994-dfc813d0-9a67-11e8-9615-9b5f28d5991c.JPG)

**Comment by andydandy74** [comment]
I can't reproduce this. Please provide more details.
![grafik](https://user-images.githubusercontent.com/3014437/43864446-fe1b8828-9b5f-11e8-927a-ee87fc6d0a81.png)

**Comment by andydandy74** [comment]
Please re-open if this is still an issue
