### ISSUE TITLE
All Family Types of Category Dynamo 2.0

### ISSUE THREAD

**Issue by DanielHurtubise** [andydandy74/ClockworkForDynamo#219]
**Describe the bug**
I believe that after upgrading the archi-lab package this node stopped working properly (would not pass the FamilyTypes)

After editing the node and removing the Revit.Elements.Category the node behava properly
![image](https://user-images.githubusercontent.com/4299930/45382276-01bda700-b608-11e8-893d-eb6f96e9ebbc.png)

**Steps to Reproduce**
Upgrade to the latest Archi-lab packages

**Expected behavior**
A list of Family Types

**My setup**
- Operating System: Windows 10
- Dynamo version: 2,0.1
- Clockwork version: 2.1.0

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [X ] I am running a *supported* Clockwork version
- [ X] I am running the *latest available* Clockwork version
- [X ] My installed version of Clockwork matches the Dynamo version it's installed for
- [X ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [X ] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by ksobon** [comment]
@andydandy74 mhmmmm sorry Andy.

**Comment by andydandy74** [comment]
For now, let's not force the category type on the input.
Here's a list of affected nodes:
* All Families of Category
* All Family Types of Category Dynamo
* All Placed Family Types of Category
* All View-Dependent Family Instances Of Category
* Category.Type
* Element.SetSubCategory

**Comment by andydandy74** [comment]
Fix will be in the next release
