### ISSUE TITLE
element.externalFileReferencePath and bim 360 docs

### ISSUE THREAD

**Issue by D-Crambert** [andydandy74/ClockworkForDynamo#220]
**Describe the bug**

When using bim360 cloud docs to save a common keynote .txt file (via autodesk desktop   connector module) I can't get the path to load the keynotetable list in dynamo.

**Steps to Reproduce**
One keynote txt file saved on a cloud server (bim360docs) accessible in revit through revit with desktop connector.
+ dynamo set : attached image with element.externalFileReferencePath node
![dynamo element externalfilereferencepath](https://user-images.githubusercontent.com/38525185/45717064-16b2b100-bb99-11e8-9c39-c872b482d1bb.JPG)

**Expected behavior**
that it finds the "BIM 360://..." path of the keynote table
![keynote settings cloud path](https://user-images.githubusercontent.com/38525185/45717066-174b4780-bb99-11e8-8787-88fe966d3d76.JPG)

**My setup**

- Operating System: Windows 10 1803
- Dynamo version: 2.01
- Clockwork version: 2.1

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running a *supported* Clockwork version
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
@D-Crambert - I do not have a BIM360 account. Could you provide a minimal Revit model where the keynote settings point to a BIM360 resource?

**Comment by andydandy74** [comment]
@D-Crambert Closing this issue since I haven't heard back from you. Fell free to re-open with the information I asked for.
