### ISSUE TITLE
BuiltInParameter.ByName not working in 2.1.0

### ISSUE THREAD

**Issue by CyrilWaechter** [andydandy74/ClockworkForDynamo#234]
**Describe the bug**
The node return null whatever the input string I enter (eg. CURVE). The same node works in Dynamo 1.3.3.4111 with Clockwork 1.32.0 and return 80 results.

**Steps to Reproduce**
1. Add a string input "CURVE"
2. Connect it to the BuiltInParameter.ByName input «searchFor»
2. Watch output

**Expected behavior**
Get a not null list of BuiltInParameters, ElementIDs and ParametersNames.

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.0.1.5065
- Clockwork version: 2.1.0
- Revit version: 2018.3

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running a *supported* Clockwork version
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
No problem. I’m glad it works on your end as well.
