### ISSUE TITLE
Crash on use of Room.doors

### ISSUE THREAD

**Issue by Christopherbte** [andydandy74/ClockworkForDynamo#237]
**Describe the bug**
Use of the Room.doors node makes dynamo crash

**Steps to Reproduce**
Use model and script
[Test.zip](https://github.com/andydandy74/ClockworkForDynamo/files/2620655/Test.zip)

**Expected behavior**
expected working node and result

**My setup**
- Operating System: W10
- Dynamo version: 2.0.1.5055
- Clockwork version: 2.1.0
- Revit version: 2019

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running a *supported* Clockwork version
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
@Christopherbte I couldn't reproduce the crash. Could you try this modified version of the Room.Doors node, though?
[Room.Doors___CRASHTEST.dyf.zip](https://github.com/andydandy74/ClockworkForDynamo/files/2627724/Room.Doors___CRASHTEST.dyf.zip)

**Comment by Christopherbte** [comment]
Unfortunately I couldn't get it to work. What I did was uninstall all the packages and reinstall the clockwork packages. Fingers crossed, works for now....
