### ISSUE TITLE
Element.AssociatedFamilyParameters - Allow node to check type parameters

### ISSUE THREAD

**Issue by Chrono9084** [andydandy74/ClockworkForDynamo#251]
It appears that the Element.AssociatedFamilyParameters node only checks a families instances parameters.  It would be amazing if it could also check type parameters for associations.

**Comment by andydandy74** [comment]
See my reply here: https://forum.dynamobim.com/t/check-if-a-families-nested-family-has-its-parameters-associated-from-a-project-environment/30456/11?u=andreas_dieckmann
