### ISSUE TITLE
Support for BuiltInCategories

### ISSUE THREAD

**Issue by MarkAckerley** [andydandy74/ClockworkForDynamo#253]
**What is the problem that needs solving?**
Dynamo Category drop down does not include legend components.

**How would you like to see it solved?**
A node which selects legend components in a view

**Describe alternatives you've considered**
A node which returns the Legend Component Category.

**Additional context**
I use this to automatically create legend sheets... As I can't create a legend component through the api, I put one on, then use the code to populate the rest with a text note pulling parameter values.

![image](https://user-images.githubusercontent.com/41670424/51973360-5ce81d00-2475-11e9-86ce-bf34ebfb8160.png)

I use this Python (with the active view, but I guess pulling from multiple views would be more versatile)....
```
import clr
clr.AddReference('RevitNodes')

import Revit
clr.ImportExtensions(Revit.Elements)
clr.AddReference('RevitServices')

import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

clr.AddReference('RevitAPI')
from Autodesk.Revit.DB import *
import System

doc = DocumentManager.Instance.CurrentDBDocument

builtInCats = System.Enum.GetValues(BuiltInCategory)
for i in builtInCats:
	if i.ToString() == 'OST_LegendComponents':
		bic = i
	else:
		continue
		
elems = FilteredElementCollector(doc, doc.ActiveView.Id).OfCategory(BuiltInCategory.OST_LegendComponents).WhereElementIsNotElementType().ToElements()


OUT = bic, elems,
```

Thanks,

Mark

**Comment by andydandy74** [comment]
@MarkAckerley That's a great suggestion. I'll modify Clockwork's existing collector nodes in such a way that they can take either of these as a category:
- Dynamo-wrapped category
- BuiltInCategory
- BuiltInCategory as string
![grafik](https://user-images.githubusercontent.com/3014437/52105199-1b2eb200-25ee-11e9-8281-108049439a8c.png)

**Comment by MarkAckerley** [comment]
Thanks Andy :)

**Comment by andydandy74** [comment]
Affected nodes:
- [ ] New node: All Elements of Category+ (an instance collector that can work with BiCs as well)
- [ ] Document.BuiltInCategories (needs to output categories that are not Dynamo-supported as well. Need to think about whether a boolean toggle makes sense for this node.)
- [ ] Document.ContainsElementsOfCategory (needs to use the new instance collector)
- [ ] Category.Type (needs to support BiCs in category input)
- [ ] Element.IsOfCategory (needs to support BiCs in category input)
- [ ] All Families Of Category (needs to support BiCs in category input)
- [ ] All Family Types Of Category (needs to support BiCs in category input)
- [ ] All Intersecting Elements of Category By BoundingBox (needs to support BiCs in category input)
- [ ] All Placed Family Types of Category (needs to use the new instance collector)
- [ ] All View-Dependent Family Instances Of Category (needs to support BiCs in category input)
- [ ] BuiltInCategory.ByName (needs to output categories that are not Dynamo-supported as well)

Nodes to check
- [ ] Document.ProjectParameters (may need an additional output for BiCs)
- [ ] Document.ProjectParametersByCategory (may need to support BiCs in category input)
- [ ] Category.Materials (may need to support BiCs in category input)
- [ ] Element.Category+ (may need an additional output for BiCs)
- [ ] Element.Geometry+ (may need an additional output for BiCs)
- [ ] Room.InsertsOfBoundariesByCategory (may need to support BiCs in category input)
- [ ] View.PermanentlyIsolateCategory (may need to support BiCs in category input)
- [ ] View.TemporarilyIsolateCategory (may need to support BiCs in category input)
- [ ] View.CategoryIsVisible (may need to support BiCs in category input)

**Comment by MarkAckerley** [comment]
Oh man... so much work! Let me know if there's anything I can do :)

**Comment by andydandy74** [comment]
2.x conversion:
- [ ] 
- [ ] 
- [ ] 
- [ ] 
- [ ]

**Comment by andydandy74** [comment]
- [ ] Review samples

**Comment by JPKN** [comment]
I just wanted to add, its funny that the workaround for manually doing all that work requires such a cobbled together workflow. Really appreciate the work you guys put into this, took me a minute to think of starting with a base legend view and then manipulating. The API limitation is debilitating.
