### ISSUE TITLE
Element.Location+ not supporting shape-edited floors

### ISSUE THREAD

**Issue by andydandy74** [andydandy74/ClockworkForDynamo#258]
Indent on line 97 of Python node is wrong as reported by @dimven 

- [ ] Fix in 1.3.x
- [ ] Migrate to 2.x
- [ ] Add to change log

**Comment by andydandy74** [comment]
@dimven - can you remember what the issue was exactly? It seems to work for me the way it is.

**Comment by dimven** [comment]
You needed to de-dent line 97 once because it was returning from the function before the for loop has iterating through all the faces.
