### ISSUE TITLE
Group.FromElements

### ISSUE THREAD

**Issue by gsucci** [andydandy74/ClockworkForDynamo#260]
**Describe the bug**
The group center is far away from the group (it appears in the origin of the project).

**Steps to Reproduce**
Create any group using dynamo node.

**Expected behavior**
The origin of the group (blue balls and axis) should be in the center of the group's elements' bounding box.

**My setup**
- Operating System: Win 10
- Dynamo version: 2.0.2.0
- Clockwork version: 2.1.2
- Revit version: 2018.3.1.2

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x ] I am running a *supported* Clockwork version
- [x] I am running the *latest available* Clockwork version
- [ x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x ] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
THis is currently not supported by the Revit API.
See https://forums.autodesk.com/t5/revit-api-forum/group-origin-please-add-api-to-get-amp-set/td-p/5966829
