### ISSUE TITLE
[Feature Request] Get Dependent Elements

### ISSUE THREAD

**Issue by schiette** [andydandy74/ClockworkForDynamo#262]
**What is the problem that needs solving?**

Some elements can have dependent element. When these elements get changed/deleted, the dependent elements might be silently changed/deleted as well. 

**How would you like to see it solved?**

A node that can return all the dependent elements of a given element.

**Describe alternatives you've considered**

Can't really find any node to do this in dynamo.

**Additional context**

The building coder has written an article on how this can be done over the API: https://thebuildingcoder.typepad.com/blog/2019/03/retrieving-and-snooping-dependent-elements.html#3

I believe the 2019 API adds a feature for this.

I came across this problem because I was building a dynamo graph to purge some unpurgeable items (viewport styles mainly). It worked fine, but it also silently deleted half the views in my model :)

**Comment by andydandy74** [comment]
@schiette This will be in the next release (probably in January).

**Comment by schiette** [comment]
Thanks Andreas, you're the best!
