### ISSUE TITLE
ScopeIf+ node error

### ISSUE THREAD

**Issue by AndreFernandes77** [andydandy74/ClockworkForDynamo#273]
I have an issue with Clockwork ScopeIf+ node. Its a large graph and it was working properly before.
The node now shows the warning “Warning: This custom node contains an invalid input. Please fix the input before saving the custom node.”
Rolling back Revit to a previous version isn´t an option.

Versions:
Clockwork for Dynamo 2.x
Revit 2020.1 (20.1.0.81)

Image: https://1drv.ms/u/s!Aj458y_YA6Zxg45WLQLi-jiUutScTQ
[](https://1drv.ms/u/s!Aj458y_YA6Zxg45WLQLi-jiUutScTQ)

**Comment by andydandy74** [comment]
@AndreFernandes77 Thanks for reporting. I haven't really started testing Clockwork in 2.1 so this might actually affect multiple nodes. I would assume you could fix this fairly easily on your end by renaming the two inputs to ```trueval``` and  ```falseval``` respectively.

**Comment by mjkkirschner** [comment]
Hi @andydandy74 

these warnings are just that (warnings) - they should not effect the actual execution of the node:
![Screen Shot 2019-10-18 at 3 23 25 PM](https://user-images.githubusercontent.com/508936/67122218-517f8200-f1bb-11e9-9643-e20d2832531a.png)

this is in 2.5
