### ISSUE TITLE
Wall.Orientation Errors

### ISSUE THREAD

**Issue by MWillhoit96** [andydandy74/ClockworkForDynamo#287]
**Describe the bug**
Wall.Orientation node showing invalid input in Dynamo 2.3 for Revit 2020. where input should say "walls", it shows up as ">." Possible that Revit and Dynamo changed the way walls are categorized in the API.

**Steps to Reproduce**
First I created a script using Clockwork when in Revit 2019. Since the update, Clockwork has been running smoothly, until I updated to Revit 2020.2 and Dynamo 2.3. Upon reinstalling the packages for my scripts, I noticed that this particular node was bugged.

**Expected behavior**
I expected the node to read the orientation of walls from "all Elements of Category", and output their vectors to the next node.

**My setup**
- Operating System: Windows 10
- Dynamo version: 2.3
- Clockwork version: 2.1.2
- Revit version: 2020.2

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running a *supported* Clockwork version
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
Thanks for reporting
Related to #274

**Comment by andydandy74** [comment]
@MWillhoit96 I can't reproduce this on my end. If you open the node, does the input say "walls" with a capital W?

**Comment by MWillhoit96** [comment]
The input says “wall: Revit.Elements.Wall”

**Comment by andydandy74** [comment]
That's strange. I'll release the new Clockwork version this week. Please let me know if the issue persists.

**Comment by MWillhoit96** [comment]
Thank you very much, I’ll be in touch.

**Comment by MWillhoit96** [comment]
Hi Andreas,

I just installed the latest version of clockwork for Dynamo 2.2 and the problem is persisting. I’ve attached screenshots of what is happening on my end, seems to be an issue with the naming of the wall category.

**Comment by MWillhoit96** [comment]
Andreas,

After a few minutes of looking at the custom node I figured out that it was just that “wall” needed to be “Wall”. That fixed it.
