### ISSUE TITLE
Document.ProjectParameters & Document.ProjectParametersByCategory

### ISSUE THREAD

**Issue by LuPaMi** [andydandy74/ClockworkForDynamo#331]
Hello AndyDandy,
I woud like to undestand why the both nodes aren't working. I've attached a picture for better explanation.

Thanks a lot in advance!

**Describe the bug**
Both nodes return null values.

**Expected behavior**
it would have to return values such as The parameters names, types, unit types, etc

**My setup**
- Operating System: Windows
- Dynamo version: 2.10
- Clockwork version: 2.3.0
- Revit version: 2022.0.1

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [ X] I am running a *supported* Clockwork version
- [ X] I am running the *latest available* Clockwork version
- [ ] My installed version of Clockwork matches the Dynamo version it's installed for
>>> nope. I'm running Dynamo Core 2.10.3976 and Dynamo Revit 2.10.1.4002, while Clockwork is in its version 2.3.0
- [X ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [X ] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

![Document ProjectParameters](https://user-images.githubusercontent.com/92087442/136362854-b2cd969d-8a65-4204-878a-6157802da49d.PNG)

**Comment by andydandy74** [comment]
@LuPaMi This is fixed for Revit 2022 with the latest commit. It will be in the next Clockwork update which (at the snail speed I'm going) might still be a while. Probably best if you download the changed nodes and replace them in your package directory.
