### ISSUE TITLE
Element.SetSubcategory is not changing Subcategory for Modellines

### ISSUE THREAD

**Issue by heinrichboldt** [andydandy74/ClockworkForDynamo#340]
**Describe the bug**
Goal: changing the Category from "Special Equipment" to something supporting the Workaround for unhosting Families from wall ( as presented by Paul Aubin)
in my case "Nurse Call Device"

3D-Elements in Family Editor can be changed with the Node
for Modellines we use also Subcategories, but the node does not change the Subcategory for Lines

**Expected behavior**
Collect all Elements in View, there are Modellines, ModelText, 3D-Extrusions ans other.
uses "FamilyDocument SubCategory" to get all avaliable Subcategories, 
used the names of Subcategory in "specialty equipment" to create every Subcategory in "Nurce Call Device"
changing the Category of Family
changing the Subcategory of all Elements (collected before)

added the Family with Lines and the Graph 

**My setup**
- Operating System: Win10 Version	10.0.19042 Build 19042
- Dynamo version: .2.3.1
- Clockwork version: 2.3.0
- Revit version: 20.2.70.6

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x ] I am running a *supported* Clockwork version
- [ x] I am running the *latest available* Clockwork version
- [x ] My installed version of Clockwork matches the Dynamo version it's installed for
- [x ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)
[Wall host change.zip](https://github.com/andydandy74/ClockworkForDynamo/files/8130839/Wall.host.change.zip)

**Comment by andydandy74** [comment]
@heinrichboldt This is now fixed and will be in the next release. 
In the meantime you can download the modified node from https://raw.githubusercontent.com/andydandy74/ClockworkForDynamo/master/nodes/2.x/Element.SetSubCategory.dyf
