### ISSUE TITLE
Document.ProjectParameters returns null in Revit 2023

### ISSUE THREAD

**Issue by denizmaral** [andydandy74/ClockworkForDynamo#351]
**Describe the bug**
Ich habe es auf dem Forum gesehen:
https://forum.dynamobim.com/t/did-the-document-projectparameters-clockwork-stop-in-revit-2023/84959

Als Platzhalter habe ich das Issue angelegt.

**Comment by andydandy74** [comment]
Schon gefixt, aber noch nicht auf dem Package Manager:
https://github.com/andydandy74/ClockworkForDynamo/wiki/Version-History#241
