### ISSUE TITLE
Forge Toolkit Incomptibility

### ISSUE THREAD

**Issue by veryshinything** [andydandy74/ClockworkForDynamo#353]
Hello sir,

Thank you for everything you do with Clockwork.  Been solid for so long, was surprised to find this issue when half my graphs broke this month.  I tried to reinstall and got this prompt that Forge Toolkit needed to be uninstalled.  I'm not sure if it's an Autodesk problem, the other package I was testing, or something that can be updated in clockwork.

The incompatibility happened after installing birdtools sparrow, which comes with its supporting packages that included forge toolkit.  

**My setup**
- Operating System: windows 11

- Revit version: 2021/2022
- Dynamo version: 2.6/2.12
- Clockwork version: 2.4.0

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [I'll try to get away from 1.3 in the next version, but currently no issues] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

![2023-01-24_09h21_32](https://user-images.githubusercontent.com/88289842/214363630-2425e339-0027-4e6c-a827-78b2a70f9a59.png)

**Comment by andydandy74** [comment]
Looks like there's a Clockwork node included in Forge Toolkit:

![grafik](https://user-images.githubusercontent.com/3014437/216787571-91528860-8bbd-448d-af32-2368444fc2aa.png)

I would suggest to delete the node from the dyf directory in the Forge Toolkit package.
