### ISSUE TITLE
Room.Finishes: Support for linked elements

### ISSUE THREAD

**Issue by andydandy74** [andydandy74/ClockworkForDynamo#362]
**What is the problem that needs solving?**
Room-bounding elements may be located in linked documents

**How would you like to see it solved?**
Have Room.Finishes support room-bounding element sin linked docs as well

**Comment by denizmaral** [comment]
Hast Du das Problem mit der Umrechnung der Fläche berücksichtigt? Sie könnte null rauswerfen. Ich würde in der Python-Node UnitUtils verwenden und die Flächen direkt da umrechnen.
