### ISSUE TITLE
View3D.SetSectionBox

### ISSUE THREAD

**Issue by denizmaral** [andydandy74/ClockworkForDynamo#395]
**Describe the bug**
![image](https://github.com/andydandy74/ClockworkForDynamo/assets/55183821/f66d5bf9-1bf8-4f0d-8c69-c03498464327)

**Steps to Reproduce**
(Please fill in. What did you do, step by step?)

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: ................
- Revit version: ................
- Dynamo version: ................
- Clockwork version: ................

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running the *latest available* Clockwork version
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
Revit 2024?

**Comment by denizmaral** [comment]
@andydandy74 in 2022 auch

**Comment by andydandy74** [comment]
Das Problem ist die Übergabe einer Revit-BoundingBox. Die Node erwartet eine Dynamo BoundingBox.

![grafik](https://github.com/andydandy74/ClockworkForDynamo/assets/3014437/8149b296-9c00-413d-9619-72eff695d39a)
