### ISSUE TITLE
Surface.FilterByOrientation not giving output for HorizontalDown

### ISSUE THREAD

**Issue by vishbhg** [andydandy74/ClockworkForDynamo#398]
**Describe the bug**
When used in a script, the surfaces which should be Horizontally Down are not reported in the output

**Steps to Reproduce**
Run on a Model in Revit 2023 to create a formwork model. Bottom of slabs are not picked by the node

**Expected behavior**
It should output surfaces which are below every slab and is working in tutorial by BIMTAMIN

**My setup**
- Operating System: Windows 10
- Revit version: 2023
- Dynamo version: 2.13.1
- Clockwork version: 2.6.0

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [✓] I am running the *latest available* Clockwork version
- [✓] My installed version of Clockwork matches the Dynamo version it's installed for
- [✓ ] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [✓] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

![report](https://github.com/andydandy74/ClockworkForDynamo/assets/156803121/c0441aa1-bec2-4240-9053-0ac80ac67985)

**Comment by andydandy74** [comment]
@vishbhg can you share a small test model?

**Comment by andydandy74** [comment]
Closing this for now. Feel free to re-open and provide a sample model.
