### ISSUE TITLE
FamilyInstance.ByPointInView

### ISSUE THREAD

**Issue by saw31** [andydandy74/ClockworkForDynamo#399]
**What is the problem that needs solving?**
The node does not manage lists of views/sheets, making impossible to place the same family instance into multiple sheets.

**How would you like to see it solved?**
I did a small change to the python script of the node. See green on screenshot.

**Describe alternatives you've considered**
A further improvement would be to manage multiple lists, ie. 20 family instances and 20 sheets passed to the node.

**Additional context**
![image](https://github.com/andydandy74/ClockworkForDynamo/assets/160093592/8b87f1be-fc88-4015-8933-c42af5ad1635)

![image](https://github.com/andydandy74/ClockworkForDynamo/assets/160093592/f93f9b57-54ac-454e-88e2-bcaaeadaf4ae)

**Comment by andydandy74** [comment]
@saw31 - I've rewritten the node entirely. It now accepts all inputs (points, family types and views) either as singletons or lists for maximum flexibility. This will be in the upcoming release of v2.12.0
