### ISSUE TITLE
All Family Types Of Category does not work

### ISSUE THREAD

**Issue by bramvdwoerdt** [andydandy74/ClockworkForDynamo#426]
**Describe the bug**
I input a list of categories, but i don't get a list of familyTypes as outputs
![image](https://github.com/user-attachments/assets/ac8b07ad-45c7-4753-9984-4a51a6402249)

**Steps to Reproduce**
See diagram above

**Expected behavior**
output should be a list of familyTypes

**My setup**
- Operating System: windows 10 business
- Revit version: Revit 23
- Dynamo version: 2.16
- Clockwork version: 2.6

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [ X] I am running the *latest available* Clockwork version
- [ X] My installed version of Clockwork matches the Dynamo version it's installed for
- [ X] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [ X] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by denizmaral** [comment]
Hello, it works fine for me. Normally category input should be shown in red but I see in your screenshot something different:

![image](https://github.com/user-attachments/assets/ffcd2676-f358-4019-97da-be87708ad1e4)

**Comment by andydandy74** [comment]
@bramvdwoerdt I made some changes to this node for the next release which may fix your issue. Can you download the node from here (https://github.com/andydandy74/ClockworkForDynamo/blob/master/nodes/2.x/All%20Family%20Types%20Of%20Category.dyf), replace it in your local package folder and try again?
![grafik](https://github.com/user-attachments/assets/b8afd0e4-4f14-42d6-8d5c-c0f51cdd7705)

**Comment by bramvdwoerdt** [comment]
I replaced the node but the issue is still the same unfortunately
![image](https://github.com/user-attachments/assets/2982fe9c-87be-4a2c-a0ef-f5b8c156ef19)

**Comment by denizmaral** [comment]
There is a problem with default values. Like I said the toggle and doc should be shown in blue and category in red (obligatory). Can you try to connect the list to doc? (that is unusual but something is wrong there). You can also try to open that custom node and send a screenshot.

**Comment by bramvdwoerdt** [comment]
I'm sorry for wasting you guys' time, i think there was something wrong with this specific instance of the node. 
![image](https://github.com/user-attachments/assets/4366740c-a352-4d20-92b7-7851867076f9)
screenshot of the node content
the node's name randomly changed when i went to take the screenshot, so i reinserted it and now it works 
![image](https://github.com/user-attachments/assets/4304f531-b5de-4e65-9c14-d54b8c644321)
thanks for the quick support though

**Comment by andydandy74** [comment]
Glad it's working for you now :-)
