### ISSUE TITLE
Rooms.Finishes node doesn't work with room using a room separator

### ISSUE THREAD

**Issue by auredor** [andydandy74/ClockworkForDynamo#433]
**Describe the bug**
(Please fill in. A clear and concise description of what the bug is. In most cases, it will be helpful if you include screenshots and/or journal files.)

in Revit 2025.2, Rooms.Finishes Node from clockwork package 2.12.0 doesn't work for room partially delimited with a room separator line. The node returns "Empty  List" for those particular rooms but it works well for the other ones. Using node code from clockwork package 2.6.0 in a custom python node returns the expected results.

**Steps to Reproduce**
(Please fill in. What did you do, step by step?)

Draw a floor plan in Revit but use a room separator line to split one of the room. In Dynamo, connect rooms collector node to rooms.Finishes node et run it

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

Get the room finishes of room using a room separator lines

**My setup**
- Operating System: .Windows 11
- Revit version: 2025.2 (was using 2023 without issue but with clockwork package 2.6.0)
- Dynamo version: 3.2.1
- Clockwork version: 2.12.0

**Housekeeping**
Please **make sure these boxes are checked** before submitting your issue:
- [ x] I am running the *latest available* Clockwork version (2.12.2 because 3.0 in not available yet through the package manager...)
- [ ] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do *not* have multiple versions of Clockwork installed for one Dynamo version
- [x] I do *not* have any pre-Clockwork packages installed (category CAAD_RWTH in the node browser)

**Comment by andydandy74** [comment]
I could reproduce this in Revit 2024 as well. You can download the fixed node here: https://github.com/andydandy74/ClockworkForDynamo/blob/master/nodes/2.x/Room.Finishes.dyf
