### ISSUE TITLE
DetailLine.FromCurve bug

### ISSUE THREAD

**Issue by l-schmidt** [andydandy74/ClockworkForDynamo#92]
DetailLine.FromCurve does not seem to be working. I have been trying to use it with only straight lines, and even a single line and it still gives the warning shown below. I tested this out on both Revit 2015 and 2016 and updated Clockwork just to be sure.

So, I have resorted to using the deprecated DetailLine.ByCurveAndView.

My setup:
- Operating System: Windows 10
- Dynamo version: 0.9
- Revit version & build number: 16.0.428.0
20150220_1215(x64)

![dynamo_detail line error](https://cloud.githubusercontent.com/assets/15087501/13326307/9c38ce9a-dbe5-11e5-9f40-1d05bceebb20.PNG)

**Comment by andydandy74** [comment]
@l-schmidt - can you try the following:
- Edit the custom node
- From the ```view``` input remove " : View"
- Save the custom node
- Re-run the definition

Also, could you let me know which type of view that Planting Plan is?

**Comment by l-schmidt** [comment]
Removing " : View" did the trick. I had previously tried that on the curve input, but didn't think to try it on view.

It is an Area Plan.

**Comment by andydandy74** [comment]
Thought so. Dynamo does not recognize Area Plans as Views.
I have an open issue for this here: #88 
I'll fix this for the next release.
Thanks for bringing it to my attention.
