### ISSUE TITLE
Wish: Regex patterns including re.DOTALL or other flags?

### ISSUE THREAD

**Issue by josols** [andydandy74/ClockworkForDynamo#94]
### Description

Not an expert in regex AT ALL, but is it possible to include the flag DOTALL in your regex nodes in Clockwork, having problems with using the regex nodes on strings with newlines in them. 
### Housekeeping

Please **make sure these boxes are checked** before submitting your issue:
- [x] I am running one of the _supported_ Clockwork versions
- [x] I am running the _latest available version_ of Clockwork
- [x] My installed version of Clockwork matches the Dynamo version it's installed for
- [x] I do _not_ have multiple versions of Clockwork installed for one Dynamo version

**Comment by andydandy74** [comment]
Yes, this is absolutely possible. This could be an optional boolean input.

**Comment by andydandy74** [comment]
@josols - I totally forgot about this one. It'll be in the next release (1.0.3)...
